<h1> Libraries </h1>

In [1]:
# basic libraries
import os
import time
import math

import numpy as np
import pandas as pd
import datetime
from datetime import datetime as ddt
from datetime import date
import matplotlib.pylab as plt

<h1> Initialization </h1>

<h2> Percentage </h2>

In [2]:
y_percentage = np.array([0.7, 0.2, 0.6])
y_percentage

array([ 0.7,  0.2,  0.6])

In [3]:
n_percentage = 1 - y_percentage
n_percentage

array([ 0.3,  0.8,  0.4])

<h2> Wieght </h2>

In [4]:
y_weight = 1 / y_percentage
y_weight

array([ 1.42857143,  5.        ,  1.66666667])

In [5]:
n_weight = 1 / n_percentage
n_weight

array([ 3.33333333,  1.25      ,  2.5       ])

<h2> Data </h2>

In [6]:
data = [np.array([1,1,1]), np.array([1,1,0]), np.array([1,0,1]), np.array([1,0,0]), 
        np.array([0,1,1]), np.array([0,1,0]), np.array([0,0,1]), np.array([0,0,0])]

In [7]:
data_name = ['YYY', 'YYN', 'YNY', 'YNN', 'NYY', 'NYN', 'NNY', 'NNN']

In [8]:
sortdata = [np.array([0,1,0]), np.array([0,1,1]), np.array([1,1,0]), np.array([0,0,0]),
            np.array([1,1,1]), np.array([0,0,1]), np.array([1,0,0]), np.array([1,0,1])]

<h1> Calculate Scores </h1>

In [9]:
# Input: comparison data, target
def calculate_relation_score(a_t, t):
    a_conj = np.ones(3, np.int) - a_t
    y_score = np.dot(y_weight, (t - a_conj) == 1)
    n_score = np.dot(n_weight, (t - a_conj) == -1)
    return y_score + n_score

In [10]:
total_score = []
# target
for i in xrange(len(data)):
    score = []
    # comparison data
    for j in xrange(len(data)):
        score.append(calculate_relation_score(data[j], data[i]))
    total_score.append(np.array(score))
total_score = np.array(total_score).T
total_score

array([[  8.0952381 ,   6.42857143,   3.0952381 ,   1.42857143,
          6.66666667,   5.        ,   1.66666667,   0.        ],
       [  6.42857143,   8.92857143,   1.42857143,   3.92857143,
          5.        ,   7.5       ,   0.        ,   2.5       ],
       [  3.0952381 ,   1.42857143,   4.3452381 ,   2.67857143,
          1.66666667,   0.        ,   2.91666667,   1.25      ],
       [  1.42857143,   3.92857143,   2.67857143,   5.17857143,
          0.        ,   2.5       ,   1.25      ,   3.75      ],
       [  6.66666667,   5.        ,   1.66666667,   0.        ,
         10.        ,   8.33333333,   5.        ,   3.33333333],
       [  5.        ,   7.5       ,   0.        ,   2.5       ,
          8.33333333,  10.83333333,   3.33333333,   5.83333333],
       [  1.66666667,   0.        ,   2.91666667,   1.25      ,
          5.        ,   3.33333333,   6.25      ,   4.58333333],
       [  0.        ,   2.5       ,   1.25      ,   3.75      ,
          3.33333333,   5.8333333

In [11]:
for t in total_score:
    p = [float(x) for x in t]
    print "{:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}" \
                                        .format((p[0]), p[1], p[2], p[3], p[4], p[5], p[6], p[7])

 8.095,  6.429,  3.095,  1.429,  6.667,  5.000,  1.667,  0.000
 6.429,  8.929,  1.429,  3.929,  5.000,  7.500,  0.000,  2.500
 3.095,  1.429,  4.345,  2.679,  1.667,  0.000,  2.917,  1.250
 1.429,  3.929,  2.679,  5.179,  0.000,  2.500,  1.250,  3.750
 6.667,  5.000,  1.667,  0.000, 10.000,  8.333,  5.000,  3.333
 5.000,  7.500,  0.000,  2.500,  8.333, 10.833,  3.333,  5.833
 1.667,  0.000,  2.917,  1.250,  5.000,  3.333,  6.250,  4.583
 0.000,  2.500,  1.250,  3.750,  3.333,  5.833,  4.583,  7.083


In [12]:
total_relation = []
for i in xrange(len(total_score)):
    total_relation.append(total_score.T[i] / total_score[i][i])
total_relation = np.array(total_relation).T
total_relation

array([[ 1.        ,  0.72      ,  0.71232877,  0.27586207,  0.66666667,
         0.46153846,  0.26666667,  0.        ],
       [ 0.79411765,  1.        ,  0.32876712,  0.75862069,  0.5       ,
         0.69230769,  0.        ,  0.35294118],
       [ 0.38235294,  0.16      ,  1.        ,  0.51724138,  0.16666667,
         0.        ,  0.46666667,  0.17647059],
       [ 0.17647059,  0.44      ,  0.61643836,  1.        ,  0.        ,
         0.23076923,  0.2       ,  0.52941176],
       [ 0.82352941,  0.56      ,  0.38356164,  0.        ,  1.        ,
         0.76923077,  0.8       ,  0.47058824],
       [ 0.61764706,  0.84      ,  0.        ,  0.48275862,  0.83333333,
         1.        ,  0.53333333,  0.82352941],
       [ 0.20588235,  0.        ,  0.67123288,  0.24137931,  0.5       ,
         0.30769231,  1.        ,  0.64705882],
       [ 0.        ,  0.28      ,  0.28767123,  0.72413793,  0.33333333,
         0.53846154,  0.73333333,  1.        ]])

In [13]:
for t in total_relation:
    p = [float(x) for x in t]
    print "{:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}, {:>6.3f}" \
                                        .format((p[0]), p[1], p[2], p[3], p[4], p[5], p[6], p[7])

 1.000,  0.720,  0.712,  0.276,  0.667,  0.462,  0.267,  0.000
 0.794,  1.000,  0.329,  0.759,  0.500,  0.692,  0.000,  0.353
 0.382,  0.160,  1.000,  0.517,  0.167,  0.000,  0.467,  0.176
 0.176,  0.440,  0.616,  1.000,  0.000,  0.231,  0.200,  0.529
 0.824,  0.560,  0.384,  0.000,  1.000,  0.769,  0.800,  0.471
 0.618,  0.840,  0.000,  0.483,  0.833,  1.000,  0.533,  0.824
 0.206,  0.000,  0.671,  0.241,  0.500,  0.308,  1.000,  0.647
 0.000,  0.280,  0.288,  0.724,  0.333,  0.538,  0.733,  1.000


<h1> Calculate Rank </h1>

In [14]:
total_index = []
for i in xrange(len(total_score.T)):
    index = total_score.T[i].argsort()[::-1]+1
    total_index.append(np.array(index))
total_index = np.array(total_index).T
total_index

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [5, 6, 1, 2, 6, 5, 5, 6],
       [2, 1, 7, 8, 1, 2, 8, 7],
       [6, 5, 4, 3, 7, 8, 6, 4],
       [3, 4, 5, 6, 2, 1, 3, 5],
       [7, 8, 2, 1, 8, 7, 1, 2],
       [4, 3, 8, 7, 3, 4, 4, 3],
       [8, 7, 6, 5, 4, 3, 2, 1]])

In [15]:
total_rank = []
for i in xrange(len(total_index.T)):
    rank = total_index.T[i].argsort()+1
    total_rank.append(np.array(rank))
total_rank = np.array(total_rank).T
total_rank

array([[1, 3, 2, 6, 3, 5, 6, 8],
       [3, 1, 6, 2, 5, 3, 8, 6],
       [5, 7, 1, 4, 7, 8, 5, 7],
       [7, 5, 4, 1, 8, 7, 7, 4],
       [2, 4, 5, 8, 1, 2, 2, 5],
       [4, 2, 8, 5, 2, 1, 4, 2],
       [6, 8, 3, 7, 4, 6, 1, 3],
       [8, 6, 7, 3, 6, 4, 3, 1]])

<h1> Sorted Data </h1>

In [16]:
stotal_score = []
# target
for i in xrange(len(sortdata)):
    score = []
    # comparison data
    for j in xrange(len(sortdata)):
        score.append(calculate_relation_score(sortdata[j], sortdata[i]))
    stotal_score.append(np.array(score))
stotal_score = np.array(stotal_score).T
stotal_score

array([[ 10.83333333,   8.33333333,   7.5       ,   5.83333333,
          5.        ,   3.33333333,   2.5       ,   0.        ],
       [  8.33333333,  10.        ,   5.        ,   3.33333333,
          6.66666667,   5.        ,   0.        ,   1.66666667],
       [  7.5       ,   5.        ,   8.92857143,   2.5       ,
          6.42857143,   0.        ,   3.92857143,   1.42857143],
       [  5.83333333,   3.33333333,   2.5       ,   7.08333333,
          0.        ,   4.58333333,   3.75      ,   1.25      ],
       [  5.        ,   6.66666667,   6.42857143,   0.        ,
          8.0952381 ,   1.66666667,   1.42857143,   3.0952381 ],
       [  3.33333333,   5.        ,   0.        ,   4.58333333,
          1.66666667,   6.25      ,   1.25      ,   2.91666667],
       [  2.5       ,   0.        ,   3.92857143,   3.75      ,
          1.42857143,   1.25      ,   5.17857143,   2.67857143],
       [  0.        ,   1.66666667,   1.42857143,   1.25      ,
          3.0952381 ,   2.9166666

In [17]:
stotal_index = []
for i in xrange(len(stotal_score.T)):
    index = stotal_score.T[i].argsort()[::-1]+1
    stotal_index.append(np.array(index))
stotal_index = np.array(stotal_index).T
stotal_index

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [2, 1, 1, 1, 2, 2, 3, 5],
       [3, 5, 5, 6, 3, 4, 4, 6],
       [4, 6, 2, 7, 1, 1, 8, 7],
       [5, 3, 7, 2, 8, 8, 1, 2],
       [6, 4, 4, 3, 6, 5, 5, 3],
       [7, 8, 8, 8, 7, 7, 6, 4],
       [8, 7, 6, 5, 4, 3, 2, 1]])

In [18]:
stotal_rank = []
for i in xrange(len(stotal_index.T)):
    rank = stotal_index.T[i].argsort()+1
    stotal_rank.append(np.array(rank))
stotal_rank = np.array(stotal_rank).T
stotal_rank

array([[1, 2, 2, 2, 4, 4, 5, 8],
       [2, 1, 4, 5, 2, 2, 8, 5],
       [3, 5, 1, 6, 3, 8, 2, 6],
       [4, 6, 6, 1, 8, 3, 3, 7],
       [5, 3, 3, 8, 1, 6, 6, 2],
       [6, 4, 8, 3, 6, 1, 7, 3],
       [7, 8, 5, 4, 7, 7, 1, 4],
       [8, 7, 7, 7, 5, 5, 4, 1]])